name: Run Newman Tests
on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

  steps:
          - uses: actions/checkout@v3.3.0

          - name: Install Node
            uses: actions/setup-node@v3

          - name: Install newman
            run: npm install newman
          - name: Run tests
            run: newman run TestCollection.json -e NewmanTestEnvironment.json